### ISSUE TITLE
Text component sometimes causes a malfunction

### ISSUE THREAD

**Issue by paiext** [pureqml/qmlcore#176] opened 2020-02-04 04:53 UTC
The following codes cause the app to become unresponsive:
If you change myText.text to "Foo" or remove the horizontalCenter  anchor option, the app will run normally.

In addition, this symptom does not occur on my desktop, but only on my laptop.

```
Rectangle {
  width: 60;
  height: 30;
  radius: 5; 
  border.width: 1;
  border.color: 'red';
  Text {
    anchors.horizontalCenter: parent.horizontalCenter;      
    color: 'white';
    font.pixelSize: 12;
    font.family: "Tahoma";        
    text: 'Get In';
  }    
} 
```

**Comment by whoozle** [comment] 2020-02-04 10:36
is it with the latest qmlcore? :|

**Comment by paiext** [comment] 2020-02-04 21:28
@whoozle > is it with the latest qmlcore? :|

of course, i checked it out several times 😃

**Comment by whoozle** [comment] 2020-02-05 11:57
Even though I could not reproduce it I reverted 48fff9c181b3164cd22afad9041d5d394e0a2910 as it should be fixed differently (give -1 padding on height: paintedHeight

**Comment by whoozle** [comment] 2020-02-05 11:59
ignore comment above, I've modified example to make it happen every time :)

**Comment by whoozle** [comment] 2020-02-05 12:00
```
Rectangle {
  width: parent.width;
  height: 30;
  radius: 5; 
  border.width: 1;
  border.color: 'red';
  color: 'gray';
  Text {
    anchors.horizontalCenter: parent.horizontalCenter;      
    color: 'white';
    font.pixelSize: parent.width / 10;
    font.family: "Tahoma";        
    text: 'Get In';
    onWidthChanged: { log(value); }
  }    
} 
```

just open inspector window and drag right side of HTML view to the right, eventually it will stuck in loop. I'm pretty sure it's rounding error, but I have to think how to tolerate it.

**Closed** 2020-02-05 12:16 UTC

**Comment by whoozle** [comment] 2020-02-05 12:22
I figured out what happened and it's really weird. 

Returned sizes have 1px difference. You're attaching text's center using anchor, this means we have to know text size to properly calculate position (left: -width/2)

Text size dependencies are bi-directional. On one hand we have default `width: paintedWidth` rule, on other hand if you're setting `width` yourself, you may enforce limit on text size. 

So what happens: 
1. Someone calls layoutText, and it returns some value, let's say 71
2. Text handles the fact that width has changed, and trigger layout again (unfortunately this overhead is hardly fixable). 
3. The same input, the same sizes, the same styles, etc, result in size 70. We trigger layout again, as you may want to recalculate text bounds and it returns 71, 70, 71, 70. 

I have similar effect in this textarea in github. Adding the same letter over and over again, gives +1/-1 and makes the lower bound of textarea jump up and down

![image](https://user-images.githubusercontent.com/480115/73841299-38561c00-4812-11ea-8e63-0c42c7107631.png)
